#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[0]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[2]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[6]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[7]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[9]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[3]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[4]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[5]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[8]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/DVSAERData_AI[10]}]
#set_property MARK_DEBUG true [get_nets brd_i/testAERDVSSM_0/DVSAERAck_SBO]
#set_property MARK_DEBUG true [get_nets brd_i/testAERDVSSM_0/DVSAERReq_ABI]
#set_property MARK_DEBUG true [get_nets brd_i/testAERDVSSM_0/DVSAERReset_SBO]
#set_property MARK_DEBUG true [get_nets brd_i/testAERDVSSM_0/U0/DVSAERAck_SBO]

#set_property MARK_DEBUG true [get_nets brd_i/testAERDVSSM_0/U0/dvsAerFifo/AlmostEmptyReg_S]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/aerAckCounter/Count_DP[0]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/aerAckCounter/Count_DP[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/aerAckCounter/Count_DP[2]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/aerAckCounter/Count_DP[3]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/State_DP[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/State_DP[2]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerSMTest/State_DP[0]}]

#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/DVSAERFifoControlIn_S[WriteSide][Write_S]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/DVSAERFifoControlOut_S[WriteSide][AlmostFull_S]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/FIFOState_S[Empty_S]}]

#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/DVSAERFifoControlOut_S[ReadSide][AlmostEmpty_S]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/DVSAERFifoControlOut_S[ReadSide][Empty_S]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/FifoControl_SO[WriteSide][AlmostFull_S]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/State_DP_reg[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/State_DP_reg[0]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/readSideOutputDelayReg/State_DP_reg[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/dvsAerFifo/readSideOutputDelayReg/State_DP_reg[0]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DN[0]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DN[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DN[2]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DN[3]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DP[0]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DP[1]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DP[2]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DP[3]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DN[4]}]
#set_property MARK_DEBUG true [get_nets {brd_i/testAERDVSSM_0/U0/multiplexerSM/State_DP[4]}]

