// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xevfastcornerstream.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEvfastcornerstream_CfgInitialize(XEvfastcornerstream *InstancePtr, XEvfastcornerstream_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Config_BaseAddress = ConfigPtr->Config_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEvfastcornerstream_Set_config_V(XEvfastcornerstream *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEvfastcornerstream_WriteReg(InstancePtr->Config_BaseAddress, XEVFASTCORNERSTREAM_CONFIG_ADDR_CONFIG_V_DATA, Data);
}

u32 XEvfastcornerstream_Get_config_V(XEvfastcornerstream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEvfastcornerstream_ReadReg(InstancePtr->Config_BaseAddress, XEVFASTCORNERSTREAM_CONFIG_ADDR_CONFIG_V_DATA);
    return Data;
}

u64 XEvfastcornerstream_Get_status_inEventsNum(XEvfastcornerstream *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEvfastcornerstream_ReadReg(InstancePtr->Config_BaseAddress, XEVFASTCORNERSTREAM_CONFIG_ADDR_STATUS_INEVENTSNUM_DATA);
    Data += (u64)XEvfastcornerstream_ReadReg(InstancePtr->Config_BaseAddress, XEVFASTCORNERSTREAM_CONFIG_ADDR_STATUS_INEVENTSNUM_DATA + 4) << 32;
    return Data;
}

u32 XEvfastcornerstream_Get_status_inEventsNum_vld(XEvfastcornerstream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEvfastcornerstream_ReadReg(InstancePtr->Config_BaseAddress, XEVFASTCORNERSTREAM_CONFIG_ADDR_STATUS_INEVENTSNUM_CTRL);
    return Data & 0x1;
}

u64 XEvfastcornerstream_Get_status_outEventsNum(XEvfastcornerstream *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEvfastcornerstream_ReadReg(InstancePtr->Config_BaseAddress, XEVFASTCORNERSTREAM_CONFIG_ADDR_STATUS_OUTEVENTSNUM_DATA);
    Data += (u64)XEvfastcornerstream_ReadReg(InstancePtr->Config_BaseAddress, XEVFASTCORNERSTREAM_CONFIG_ADDR_STATUS_OUTEVENTSNUM_DATA + 4) << 32;
    return Data;
}

u32 XEvfastcornerstream_Get_status_outEventsNum_vld(XEvfastcornerstream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEvfastcornerstream_ReadReg(InstancePtr->Config_BaseAddress, XEVFASTCORNERSTREAM_CONFIG_ADDR_STATUS_OUTEVENTSNUM_CTRL);
    return Data & 0x1;
}

u64 XEvfastcornerstream_Get_status_cornerEventsNum(XEvfastcornerstream *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEvfastcornerstream_ReadReg(InstancePtr->Config_BaseAddress, XEVFASTCORNERSTREAM_CONFIG_ADDR_STATUS_CORNEREVENTSNUM_DATA);
    Data += (u64)XEvfastcornerstream_ReadReg(InstancePtr->Config_BaseAddress, XEVFASTCORNERSTREAM_CONFIG_ADDR_STATUS_CORNEREVENTSNUM_DATA + 4) << 32;
    return Data;
}

u32 XEvfastcornerstream_Get_status_cornerEventsNum_vld(XEvfastcornerstream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEvfastcornerstream_ReadReg(InstancePtr->Config_BaseAddress, XEVFASTCORNERSTREAM_CONFIG_ADDR_STATUS_CORNEREVENTSNUM_CTRL);
    return Data & 0x1;
}

