// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xevabmofstream.h"

extern XEvabmofstream_Config XEvabmofstream_ConfigTable[];

XEvabmofstream_Config *XEvabmofstream_LookupConfig(u16 DeviceId) {
	XEvabmofstream_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XEVABMOFSTREAM_NUM_INSTANCES; Index++) {
		if (XEvabmofstream_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XEvabmofstream_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XEvabmofstream_Initialize(XEvabmofstream *InstancePtr, u16 DeviceId) {
	XEvabmofstream_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XEvabmofstream_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XEvabmofstream_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

