// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xevabmofstream.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEvabmofstream_CfgInitialize(XEvabmofstream *InstancePtr, XEvabmofstream_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Config_BaseAddress = ConfigPtr->Config_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEvabmofstream_Set_config_V(XEvabmofstream *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEvabmofstream_WriteReg(InstancePtr->Config_BaseAddress, XEVABMOFSTREAM_CONFIG_ADDR_CONFIG_V_DATA, Data);
}

u32 XEvabmofstream_Get_config_V(XEvabmofstream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEvabmofstream_ReadReg(InstancePtr->Config_BaseAddress, XEVABMOFSTREAM_CONFIG_ADDR_CONFIG_V_DATA);
    return Data;
}

u32 XEvabmofstream_Get_status_V(XEvabmofstream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEvabmofstream_ReadReg(InstancePtr->Config_BaseAddress, XEVABMOFSTREAM_CONFIG_ADDR_STATUS_V_DATA);
    return Data;
}

u32 XEvabmofstream_Get_status_V_vld(XEvabmofstream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEvabmofstream_ReadReg(InstancePtr->Config_BaseAddress, XEVABMOFSTREAM_CONFIG_ADDR_STATUS_V_CTRL);
    return Data & 0x1;
}

