// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// config
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of configRegs_V
//        bit 15~0 - configRegs_V[15:0] (Read/Write)
//        others   - reserved
// 0x14 : reserved
// 0x18 : Data signal of ctrl_V
//        bit 31~0 - ctrl_V[31:0] (Read/Write)
// 0x1c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XEVENTSTREAMTOCONSTENCNTFRAMESTREAM_CONFIG_ADDR_CONFIGREGS_V_DATA 0x10
#define XEVENTSTREAMTOCONSTENCNTFRAMESTREAM_CONFIG_BITS_CONFIGREGS_V_DATA 16
#define XEVENTSTREAMTOCONSTENCNTFRAMESTREAM_CONFIG_ADDR_CTRL_V_DATA       0x18
#define XEVENTSTREAMTOCONSTENCNTFRAMESTREAM_CONFIG_BITS_CTRL_V_DATA       32

