// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// config
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of config_V
//        bit 31~0 - config_V[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of status_V
//        bit 31~0 - status_V[31:0] (Read)
// 0x1c : Control signal of status_V
//        bit 0  - status_V_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XEVABMOFSTREAM_CONFIG_ADDR_CONFIG_V_DATA 0x10
#define XEVABMOFSTREAM_CONFIG_BITS_CONFIG_V_DATA 32
#define XEVABMOFSTREAM_CONFIG_ADDR_STATUS_V_DATA 0x18
#define XEVABMOFSTREAM_CONFIG_BITS_STATUS_V_DATA 32
#define XEVABMOFSTREAM_CONFIG_ADDR_STATUS_V_CTRL 0x1c

