// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xevfastcornerstream.h"

extern XEvfastcornerstream_Config XEvfastcornerstream_ConfigTable[];

XEvfastcornerstream_Config *XEvfastcornerstream_LookupConfig(u16 DeviceId) {
	XEvfastcornerstream_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XEVFASTCORNERSTREAM_NUM_INSTANCES; Index++) {
		if (XEvfastcornerstream_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XEvfastcornerstream_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XEvfastcornerstream_Initialize(XEvfastcornerstream *InstancePtr, u16 DeviceId) {
	XEvfastcornerstream_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XEvfastcornerstream_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XEvfastcornerstream_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

